name: Britive-Github Federated Access for AWS Keyless via OpenID Connect

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * *'  # Runs daily at 08:00 UTC
permissions:
  id-token: write
  contents: read

jobs:
  federated-aws-access:
    runs-on: ubuntu-latest

    env:
      BRITIVE_TENANT: se-learn
      BRITIVE_PROFILE_NAME: AWS Standalone/Widgeto Prod/S3-Access-App123
      FED_PROVIDER: github-britive
      AWS_REGION: us-east-2 

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install pybritive cli
        run: |
          pip install pybritive --quiet
 
      - name: Configure Britive and AWS credential_process
        run: |
          mkdir -p ~/.aws
          # Add profile alias
          pybritive configure update profile-aliases default "$BRITIVE_PROFILE_NAME"
          # Set AWS credential_process to use pybritive federation
          cat <<EOF > ~/.aws/credentials
          [default]
          credential_process=pybritive checkout default -m awscredentialprocess -P $FED_PROVIDER
          EOF

          # Set default AWS region
          aws configure set default.region "$AWS_REGION"

      - name: Test AWS Access - List S3 Buckets
        run: |
          echo "Listing S3 buckets..."
          aws s3 ls
